
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class ClassificationMenu extends javax.swing.JPanel {

    /**
     * Creates new form ClassificationPane
     */
    public ClassificationMenu() {
        initComponents();
    }
    
    public ImageIcon expandedIcon = new ImageIcon("src/assets/Expanded.png");
    public ImageIcon collapsedIcon = new ImageIcon("src/assets/Collapsed.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classificationPane = new javax.swing.JPanel();
        classG = new javax.swing.JCheckBox();
        classPG = new javax.swing.JCheckBox();
        classM = new javax.swing.JCheckBox();
        classMA15 = new javax.swing.JCheckBox();
        classR18 = new javax.swing.JCheckBox();
        classificationToggle = new javax.swing.JButton();

        classificationPane.setBackground(new java.awt.Color(255, 0, 0));

        classG.setText("G");

        classPG.setText("PG");

        classM.setText("M");

        classMA15.setText("MA15+");

        classR18.setText("R18+");

        javax.swing.GroupLayout classificationPaneLayout = new javax.swing.GroupLayout(classificationPane);
        classificationPane.setLayout(classificationPaneLayout);
        classificationPaneLayout.setHorizontalGroup(
            classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classM)
                    .addComponent(classG)
                    .addComponent(classR18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classPG)
                    .addComponent(classMA15))
                .addGap(28, 28, 28))
        );
        classificationPaneLayout.setVerticalGroup(
            classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classificationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classG)
                    .addComponent(classPG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(classificationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classM)
                    .addComponent(classMA15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classR18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        classificationToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expanded.png"))); // NOI18N
        classificationToggle.setText("Classification");
        classificationToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        classificationToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        classificationToggle.setIconTextGap(35);
        classificationToggle.setMinimumSize(new java.awt.Dimension(193, 23));
        classificationToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificationToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classificationToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classificationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classificationToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classificationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classificationToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificationToggleActionPerformed
        classificationPane.setVisible(!classificationPane.isVisible());
        if (classificationPane.isVisible()) {
            classificationToggle.setIcon(expandedIcon);
        } else {
            classificationToggle.setIcon(collapsedIcon);
        }
    }//GEN-LAST:event_classificationToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox classG;
    private javax.swing.JCheckBox classM;
    private javax.swing.JCheckBox classMA15;
    private javax.swing.JCheckBox classPG;
    private javax.swing.JCheckBox classR18;
    private javax.swing.JPanel classificationPane;
    private javax.swing.JButton classificationToggle;
    // End of variables declaration//GEN-END:variables
}
