/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class GameEntry extends javax.swing.JPanel {

    /**
     * Creates new form GameEntry
     */
    public GameEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spacer = new javax.swing.JLabel();
        boxArt = new javax.swing.JLabel();
        gameName = new javax.swing.JLabel();
        classification = new javax.swing.JLabel();
        MACL = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        playStatus = new javax.swing.JLabel();
        starRating2 = new StarRating();

        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(5);
        setLayout(horizontalLayout1);
        add(spacer);

        boxArt.setText("Image");
        add(boxArt);

        gameName.setText("Title");
        add(gameName);

        classification.setText("Classification");
        add(classification);

        MACL.setText("MACL");
        add(MACL);

        year.setText("Release Year");
        add(year);

        playStatus.setText("Play Status");
        add(playStatus);
        add(starRating2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MACL;
    private javax.swing.JLabel boxArt;
    private javax.swing.JLabel classification;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel playStatus;
    private javax.swing.JLabel spacer;
    private StarRating starRating2;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
