
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class MACLMenu extends javax.swing.JPanel {

    /**
     * Creates new form MACLPane
     */
    public MACLMenu() {
        initComponents();
    }
    
    public ImageIcon expandedIcon = new ImageIcon("src/assets/Expanded.png");
    public ImageIcon collapsedIcon = new ImageIcon("src/assets/Collapsed.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MACLPane = new javax.swing.JPanel();
        MACLPane.setVisible(false);
        min = new javax.swing.JLabel();
        minMACL = new javax.swing.JTextField();
        max = new javax.swing.JLabel();
        maxMACL = new javax.swing.JTextField();
        MACLToggle = new javax.swing.JButton();

        MACLPane.setBackground(new java.awt.Color(255, 0, 0));

        min.setText("Min:");

        minMACL.setText("min");

        max.setText("Max:");

        maxMACL.setText("max");

        javax.swing.GroupLayout MACLPaneLayout = new javax.swing.GroupLayout(MACLPane);
        MACLPane.setLayout(MACLPaneLayout);
        MACLPaneLayout.setHorizontalGroup(
            MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MACLPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min)
                    .addComponent(max))
                .addGap(18, 18, 18)
                .addGroup(MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minMACL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxMACL, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MACLPaneLayout.setVerticalGroup(
            MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MACLPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(minMACL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MACLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(max)
                    .addComponent(maxMACL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MACLToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Collapsed.png"))); // NOI18N
        MACLToggle.setText("MACL");
        MACLToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MACLToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        MACLToggle.setIconTextGap(57);
        MACLToggle.setMinimumSize(new java.awt.Dimension(193, 23));
        MACLToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MACLToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MACLPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MACLToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MACLToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MACLPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MACLToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MACLToggleActionPerformed
        MACLPane.setVisible(!MACLPane.isVisible());
        if (MACLPane.isVisible()) {
            MACLToggle.setIcon(expandedIcon);
        } else {
            MACLToggle.setIcon(collapsedIcon);
        }
    }//GEN-LAST:event_MACLToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MACLPane;
    private javax.swing.JButton MACLToggle;
    private javax.swing.JLabel max;
    private javax.swing.JTextField maxMACL;
    private javax.swing.JLabel min;
    private javax.swing.JTextField minMACL;
    // End of variables declaration//GEN-END:variables
}
