
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class RatingMenu extends javax.swing.JPanel {

    /**
     * Creates new form RatingMenu
     */
    public RatingMenu() {
        initComponents();
    }
    
    public ImageIcon expandedIcon = new ImageIcon("src/assets/Expanded.png");
    public ImageIcon collapsedIcon = new ImageIcon("src/assets/Collapsed.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingPane = new javax.swing.JPanel();
        ratingPane.setVisible(false);
        noStars = new javax.swing.JCheckBox();
        oneStar = new javax.swing.JCheckBox();
        twoStars = new javax.swing.JCheckBox();
        threeStars = new javax.swing.JCheckBox();
        fourStars = new javax.swing.JCheckBox();
        fiveStars = new javax.swing.JCheckBox();
        ratingToggle = new javax.swing.JButton();

        ratingPane.setBackground(new java.awt.Color(255, 0, 0));

        noStars.setText("None");

        oneStar.setText("1 Star");

        twoStars.setText("2 Stars");

        threeStars.setText("3 Stars");

        fourStars.setText("4 Stars");

        fiveStars.setText("5 Stars");

        javax.swing.GroupLayout ratingPaneLayout = new javax.swing.GroupLayout(ratingPane);
        ratingPane.setLayout(ratingPaneLayout);
        ratingPaneLayout.setHorizontalGroup(
            ratingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noStars)
                    .addComponent(oneStar)
                    .addComponent(twoStars)
                    .addComponent(threeStars)
                    .addComponent(fourStars)
                    .addComponent(fiveStars))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ratingPaneLayout.setVerticalGroup(
            ratingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noStars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneStar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoStars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threeStars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourStars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fiveStars)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ratingToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Collapsed.png"))); // NOI18N
        ratingToggle.setText("Rating");
        ratingToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ratingToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ratingToggle.setIconTextGap(53);
        ratingToggle.setMinimumSize(new java.awt.Dimension(193, 23));
        ratingToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ratingPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratingToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ratingToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingToggleActionPerformed
        ratingPane.setVisible(!ratingPane.isVisible());
        if (ratingPane.isVisible()) {
            ratingToggle.setIcon(expandedIcon);
        } else {
            ratingToggle.setIcon(collapsedIcon);
        }
    }//GEN-LAST:event_ratingToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fiveStars;
    private javax.swing.JCheckBox fourStars;
    private javax.swing.JCheckBox noStars;
    private javax.swing.JCheckBox oneStar;
    private javax.swing.JPanel ratingPane;
    private javax.swing.JButton ratingToggle;
    private javax.swing.JCheckBox threeStars;
    private javax.swing.JCheckBox twoStars;
    // End of variables declaration//GEN-END:variables
}
