
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class StarRating extends javax.swing.JPanel {

    /**
     * Creates new form StarRating
     */
    public StarRating() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spacer = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        spacer1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(370, 64));
        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(10);
        setLayout(horizontalLayout1);
        add(spacer);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DeselectedStar.png"))); // NOI18N
        add(star1);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DeselectedStar.png"))); // NOI18N
        add(star2);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DeselectedStar.png"))); // NOI18N
        add(star3);

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DeselectedStar.png"))); // NOI18N
        add(star4);

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DeselectedStar.png"))); // NOI18N
        star5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        star5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(star5);
        add(spacer1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel spacer;
    private javax.swing.JLabel spacer1;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
