
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class YearMenu extends javax.swing.JPanel {

    /**
     * Creates new form YearMenu
     */
    public YearMenu() {
        initComponents();
    }
    
    public ImageIcon expandedIcon = new ImageIcon("src/assets/Expanded.png");
    public ImageIcon collapsedIcon = new ImageIcon("src/assets/Collapsed.png");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearPane = new javax.swing.JPanel();
        maxMACL = new javax.swing.JTextField();
        max = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        minMACL = new javax.swing.JTextField();
        yearToggle = new javax.swing.JButton();

        yearPane.setBackground(new java.awt.Color(255, 0, 0));

        maxMACL.setText("max");

        max.setText("Max:");

        min.setText("Min:");

        minMACL.setText("min");

        javax.swing.GroupLayout yearPaneLayout = new javax.swing.GroupLayout(yearPane);
        yearPane.setLayout(yearPaneLayout);
        yearPaneLayout.setHorizontalGroup(
            yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min)
                    .addComponent(max))
                .addGap(18, 18, 18)
                .addGroup(yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minMACL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxMACL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yearPaneLayout.setVerticalGroup(
            yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(minMACL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yearPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(max)
                    .addComponent(maxMACL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        yearToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Expanded.png"))); // NOI18N
        yearToggle.setText("Year");
        yearToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        yearToggle.setIconTextGap(60);
        yearToggle.setMinimumSize(new java.awt.Dimension(193, 23));
        yearToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(yearPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yearToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearToggleActionPerformed
        yearPane.setVisible(!yearPane.isVisible());
        if (yearPane.isVisible()) {
            yearToggle.setIcon(expandedIcon);
        } else {
            yearToggle.setIcon(collapsedIcon);
        }
    }//GEN-LAST:event_yearToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel max;
    private javax.swing.JTextField maxMACL;
    private javax.swing.JLabel min;
    private javax.swing.JTextField minMACL;
    private javax.swing.JPanel yearPane;
    private javax.swing.JButton yearToggle;
    // End of variables declaration//GEN-END:variables
}
