/**
 *
 * @author dylan
 */
public class GameEntry extends javax.swing.JPanel {

    /**
     * Creates new form GameEntry
     */
    public GameEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frontSpacer = new javax.swing.JLabel();
        boxArt = new javax.swing.JLabel();
        gameName = new javax.swing.JLabel();
        classification = new javax.swing.JLabel();
        mACL = new javax.swing.JLabel();
        realeaseYear = new javax.swing.JLabel();
        playStatus = new javax.swing.JLabel();
        starRating = new StarRating();

        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(5);
        setLayout(horizontalLayout1);
        add(frontSpacer);

        boxArt.setText("Box Art");
        add(boxArt);

        gameName.setText("Title");
        add(gameName);

        classification.setText("Classification");
        add(classification);

        mACL.setText("MACL");
        add(mACL);

        realeaseYear.setText("Release Year");
        add(realeaseYear);

        playStatus.setText("Play Status");
        add(playStatus);
        add(starRating);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel boxArt;
    public javax.swing.JLabel classification;
    private javax.swing.JLabel frontSpacer;
    public javax.swing.JLabel gameName;
    public javax.swing.JLabel mACL;
    public javax.swing.JLabel playStatus;
    public javax.swing.JLabel realeaseYear;
    private StarRating starRating;
    // End of variables declaration//GEN-END:variables
}
