/**
 *
 * @author dylan
 */
public class GameEntry extends javax.swing.JPanel {

    /**
     * Creates new form GameEntry
     */
    public GameEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrontSpacer = new javax.swing.JLabel();
        lblBoxArt = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        lblClassification = new javax.swing.JLabel();
        lblMACL = new javax.swing.JLabel();
        lblRealeaseYear = new javax.swing.JLabel();
        lblPlayStatus = new javax.swing.JLabel();
        starRating1 = new StarRating();

        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(5);
        setLayout(horizontalLayout1);
        add(lblFrontSpacer);

        lblBoxArt.setText("Box Art");
        add(lblBoxArt);

        lblGameName.setText("Title");
        add(lblGameName);

        lblClassification.setText("Classification");
        add(lblClassification);

        lblMACL.setText("MACL");
        add(lblMACL);

        lblRealeaseYear.setText("Release Year");
        add(lblRealeaseYear);

        lblPlayStatus.setText("Play Status");
        add(lblPlayStatus);
        add(starRating1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblBoxArt;
    public javax.swing.JLabel lblClassification;
    private javax.swing.JLabel lblFrontSpacer;
    public javax.swing.JLabel lblGameName;
    public javax.swing.JLabel lblMACL;
    public javax.swing.JLabel lblPlayStatus;
    public javax.swing.JLabel lblRealeaseYear;
    private StarRating starRating1;
    // End of variables declaration//GEN-END:variables
}
