
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author dylan
 */
public class GameDataWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameDataWindow
     */
    public GameDataWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        lblPlatform = new javax.swing.JLabel();
        cmbPlatformSelector = new javax.swing.JComboBox<>();
        lblBoxArt = new javax.swing.JLabel();
        lblBoxArtImage = new javax.swing.JLabel();
        btnLoadImage = new javax.swing.JButton();
        btnRemoveImage = new javax.swing.JButton();
        lblReleaseYear = new javax.swing.JLabel();
        cmbReleaseYearSelector = new javax.swing.JComboBox<>();
        lblPlayStatus = new javax.swing.JLabel();
        cmbPlayStatus = new javax.swing.JComboBox<>();
        lblRating = new javax.swing.JLabel();
        btnRemoveGame = new javax.swing.JButton();
        scrNotes = new javax.swing.JScrollPane();
        txaNotes = new javax.swing.JTextArea();
        lblClassification = new javax.swing.JLabel();
        cmbClassificationSelector = new javax.swing.JComboBox<>();
        lblMACL = new javax.swing.JLabel();
        txtMACLEntry = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        srtRatingSelector = new StarRating();
        btnSetRatingZero = new javax.swing.JButton();
        lblNotes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level-Up Library - Game Data Window");

        lblTitle.setText("Game Title:");

        txtGameName.setText("Game Name");
        txtGameName.setMinimumSize(new java.awt.Dimension(250, 22));
        txtGameName.setPreferredSize(new java.awt.Dimension(250, 22));

        lblPlatform.setText("Platform:");

        cmbPlatformSelector.setPreferredSize(new java.awt.Dimension(150, 22));

        lblBoxArt.setText("Box Art Image:");

        lblBoxArtImage.setBackground(new java.awt.Color(255, 0, 0));
        lblBoxArtImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBoxArtImage.setText("Box Art Image");
        lblBoxArtImage.setMinimumSize(new java.awt.Dimension(150, 225));
        lblBoxArtImage.setPreferredSize(new java.awt.Dimension(150, 225));

        btnLoadImage.setText("Load");

        btnRemoveImage.setText("Clear");

        lblReleaseYear.setText("Release Year:");

        cmbReleaseYearSelector.setPreferredSize(new java.awt.Dimension(100, 22));

        lblPlayStatus.setText("Play Status:");

        cmbPlayStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NP", "IP", "FG", "FS", "AB" }));

        lblRating.setText("Rating:");

        btnRemoveGame.setText("Remove");

        txaNotes.setColumns(20);
        txaNotes.setLineWrap(true);
        txaNotes.setRows(5);
        scrNotes.setViewportView(txaNotes);

        lblClassification.setText("Classification:");

        cmbClassificationSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "PG", "M", "MA15+", "R18+" }));
        cmbClassificationSelector.setToolTipText("");

        lblMACL.setText("MACL:");

        txtMACLEntry.setText("0");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");

        srtRatingSelector.setIsSelector(true);

        btnSetRatingZero.setText("Clear");
        btnSetRatingZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRatingZeroActionPerformed(evt);
            }
        });

        lblNotes.setText("Notes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRating, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(srtRatingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbReleaseYearSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbPlayStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMACL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbClassificationSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMACLEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblReleaseYear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnLoadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnRemoveImage))
                                                    .addComponent(lblBoxArt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(29, 29, 29)
                                        .addComponent(lblBoxArtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSetRatingZero, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(lblPlatform, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                    .addComponent(lblNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPlatformSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(btnRemoveGame)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(lblPlatform)
                        .addComponent(cmbPlatformSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRemoveGame)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBoxArtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNotes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblBoxArt)
                                .addGap(43, 43, 43)
                                .addComponent(btnLoadImage)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveImage)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReleaseYear)
                                    .addComponent(cmbReleaseYearSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlayStatus)
                                    .addComponent(cmbPlayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblClassification)
                                    .addComponent(cmbClassificationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMACL)
                                    .addComponent(txtMACLEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSetRatingZero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(srtRatingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String[] sarCurrentGameData = new String[10];
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSetRatingZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRatingZeroActionPerformed
        srtRatingSelector.selectRatingZero();
    }//GEN-LAST:event_btnSetRatingZeroActionPerformed

    public void setYearSelector() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        Date date = new Date();
        int currentYear = Integer.parseInt(dateFormat.format(date));
        
        for (int i = 1958; i < currentYear + 1; i++) {
            cmbReleaseYearSelector.addItem(String.valueOf(i));
        }
    }
    
    public void loadCurrentGameData(String[] sarData) {
        // Stucture: [id, platform, boxart path, title, length, class, year, status, rating, notes]
        sarCurrentGameData = sarData;
        
        for (int i = 0; i < MainWindow.intPlatformCount; i++) {
            cmbPlatformSelector.addItem(MainWindow.sarPlatformList[i]);
        }
        cmbPlatformSelector.getModel().setSelectedItem(sarData[1]);
        
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(System.getProperty("user.dir") + "\\src\\main\\resources\\" + sarData[2]));
        } catch (IOException e) {
            System.out.println("Unable to load boxart image for GameEntry Update");
        }
        if (img != null) {
            lblBoxArtImage.setText("");
            Image dimg = img.getScaledInstance(lblBoxArtImage.getWidth(), lblBoxArtImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            lblBoxArtImage.setIcon(imageIcon);
        } else {
            lblBoxArtImage.setText("Unable to load image");
        }
        
        
        txtGameName.setText(sarData[3]);
        
        txtMACLEntry.setText(sarData[4]);
        
        cmbClassificationSelector.getModel().setSelectedItem(sarData[5]);
        
        setYearSelector();
        cmbReleaseYearSelector.getModel().setSelectedItem(sarData[6]);
        
        cmbPlayStatus.getModel().setSelectedItem(sarData[7]);
        
        srtRatingSelector.setRating(Integer.parseInt(sarData[8]));
        
        txaNotes.setText(sarData[9]);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameDataWindow().setVisible(true);
            }
        });
    }

    //<editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoadImage;
    public javax.swing.JButton btnRemoveGame;
    private javax.swing.JButton btnRemoveImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSetRatingZero;
    private javax.swing.JComboBox<String> cmbClassificationSelector;
    private javax.swing.JComboBox<String> cmbPlatformSelector;
    private javax.swing.JComboBox<String> cmbPlayStatus;
    private javax.swing.JComboBox<String> cmbReleaseYearSelector;
    private javax.swing.JLabel lblBoxArt;
    private javax.swing.JLabel lblBoxArtImage;
    private javax.swing.JLabel lblClassification;
    private javax.swing.JLabel lblMACL;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblPlayStatus;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblReleaseYear;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrNotes;
    private StarRating srtRatingSelector;
    private javax.swing.JTextArea txaNotes;
    private javax.swing.JTextField txtGameName;
    private javax.swing.JTextField txtMACLEntry;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
