/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author dylan
 */
public class PlatformTab extends javax.swing.JPanel {

    /**
     * Creates new form platformTab
     */
    public PlatformTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabScroll = new javax.swing.JScrollPane();
        tabMainPanel = new javax.swing.JPanel();
        lblSpacer = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(5);
        tabMainPanel.setLayout(verticalLayout1);
        tabMainPanel.add(lblSpacer);

        tabScroll.setViewportView(tabMainPanel);

        add(tabScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSpacer;
    public javax.swing.JPanel tabMainPanel;
    public javax.swing.JScrollPane tabScroll;
    // End of variables declaration//GEN-END:variables
}
