
import javax.swing.ImageIcon;

/**
 *
 * @author dylan
 */
public class StarRating extends javax.swing.JPanel {

    /**
     * Creates new form StarRating
     */
    public StarRating() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frontSpacer = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();

        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(5);
        setLayout(horizontalLayout1);
        add(frontSpacer);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeselectedStar.png"))); // NOI18N
        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star1MouseExited(evt);
            }
        });
        add(star1);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeselectedStar.png"))); // NOI18N
        star2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                star2MouseDragged(evt);
            }
        });
        star2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star2MouseExited(evt);
            }
        });
        add(star2);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeselectedStar.png"))); // NOI18N
        star3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                star3MouseDragged(evt);
            }
        });
        star3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star3MouseExited(evt);
            }
        });
        add(star3);

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeselectedStar.png"))); // NOI18N
        star4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                star4MouseDragged(evt);
            }
        });
        star4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star4MouseExited(evt);
            }
        });
        add(star4);

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeselectedStar.png"))); // NOI18N
        star5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                star5MouseDragged(evt);
            }
        });
        star5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star5MouseExited(evt);
            }
        });
        add(star5);
    }// </editor-fold>//GEN-END:initComponents

    private ImageIcon icnSelectedIcon = new ImageIcon(getClass().getResource("/SelectedStar.png"));
    private ImageIcon icnDeselectedIcon = new ImageIcon(getClass().getResource("/DeselectedStar.png"));
    private ImageIcon icnHighlightedIcon = new ImageIcon(getClass().getResource("/HighlightedStar.png"));
    private boolean booIsSelector = false;
    public int intSelectedRating = 0;
    
    private void star2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseEntered
        if (booIsSelector == true) {
            star1.setIcon(icnHighlightedIcon);
            star2.setIcon(icnHighlightedIcon);
        }
    }//GEN-LAST:event_star2MouseEntered

    private void star2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseExited
        if (booIsSelector == true) {
            star1.setIcon(icnDeselectedIcon);
            star2.setIcon(icnDeselectedIcon);
        }
    }//GEN-LAST:event_star2MouseExited

    private void star3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseEntered
        if (booIsSelector == true) {
            star1.setIcon(icnHighlightedIcon);
            star2.setIcon(icnHighlightedIcon);
            star3.setIcon(icnHighlightedIcon);
        }
    }//GEN-LAST:event_star3MouseEntered

    private void star3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseExited
        if (booIsSelector == true) {
            star1.setIcon(icnDeselectedIcon);
            star2.setIcon(icnDeselectedIcon);
            star3.setIcon(icnDeselectedIcon);
        }
    }//GEN-LAST:event_star3MouseExited

    private void star4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseEntered
        if (booIsSelector == true) {
            star1.setIcon(icnHighlightedIcon);
            star2.setIcon(icnHighlightedIcon);
            star3.setIcon(icnHighlightedIcon);
            star4.setIcon(icnHighlightedIcon);
        }
    }//GEN-LAST:event_star4MouseEntered

    private void star4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseExited
        if (booIsSelector == true) {
            star1.setIcon(icnDeselectedIcon);
            star2.setIcon(icnDeselectedIcon);
            star3.setIcon(icnDeselectedIcon);
            star4.setIcon(icnDeselectedIcon);
        }
    }//GEN-LAST:event_star4MouseExited

    private void star5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseEntered
        if (booIsSelector == true) {
            star1.setIcon(icnHighlightedIcon);
            star2.setIcon(icnHighlightedIcon);
            star3.setIcon(icnHighlightedIcon);
            star4.setIcon(icnHighlightedIcon);
            star5.setIcon(icnHighlightedIcon);
        }
    }//GEN-LAST:event_star5MouseEntered

    private void star5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseExited
        if (booIsSelector == true) {
            star1.setIcon(icnDeselectedIcon);
            star2.setIcon(icnDeselectedIcon);
            star3.setIcon(icnDeselectedIcon);
            star4.setIcon(icnDeselectedIcon);
            star5.setIcon(icnDeselectedIcon);
        }
    }//GEN-LAST:event_star5MouseExited
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Selection Handling">
    private void star1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseClicked
        if (booIsSelector == true) {
            intSelectedRating = 1;
            star1.setIcon(icnSelectedIcon);
        }
    }//GEN-LAST:event_star1MouseClicked

    private void star2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseDragged
        if (booIsSelector == true) {
            intSelectedRating = 2;
            star1.setIcon(icnSelectedIcon);
            star2.setIcon(icnSelectedIcon);
        }
    }//GEN-LAST:event_star2MouseDragged

    private void star3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseDragged
        if (booIsSelector == true) {
            intSelectedRating = 3;
            star1.setIcon(icnSelectedIcon);
            star2.setIcon(icnSelectedIcon);
            star3.setIcon(icnSelectedIcon);
        }
    }//GEN-LAST:event_star3MouseDragged

    private void star4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseDragged
        if (booIsSelector == true) {
            intSelectedRating = 4;
            star1.setIcon(icnSelectedIcon);
            star2.setIcon(icnSelectedIcon);
            star3.setIcon(icnSelectedIcon);
            star4.setIcon(icnSelectedIcon);
        }
    }//GEN-LAST:event_star4MouseDragged

    private void star5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseDragged
        if (booIsSelector == true) {
            intSelectedRating = 5;
            star1.setIcon(icnSelectedIcon);
            star2.setIcon(icnSelectedIcon);
            star3.setIcon(icnSelectedIcon);
            star4.setIcon(icnSelectedIcon);
            star5.setIcon(icnSelectedIcon);
        }
    }//GEN-LAST:event_star5MouseDragged

    private void star1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseExited
        if (booIsSelector == true) {
            star1.setIcon(icnDeselectedIcon);
        }
    }//GEN-LAST:event_star1MouseExited

    //<editor-fold defaultstate="collapsed" desc="Selection Highlighting">
    private void star1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseEntered
        if (booIsSelector == true) {
            star1.setIcon(icnHighlightedIcon);
        }
    }//GEN-LAST:event_star1MouseEntered
    //</editor-fold>
    
    public boolean getIsSelector() {
        return booIsSelector;
    }
    
    public void setIsSelector(boolean isSelector) {
        this.booIsSelector = isSelector;
    }
    
    private static void setRating(int intRating) {
        System.out.println(intRating);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frontSpacer;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
