/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.softwaredevelopment.level.up_library.MainWindow;

/**
 *
 * @author dylan
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srpSidebar = new javax.swing.JScrollPane();
        pnlSidebar = new javax.swing.JPanel();
        pnlSearchMenu = new com.softwaredevelopment.level.up_library.SearchMenu.SearchMenu();
        lblFilters = new javax.swing.JLabel();
        pnlClassificationMenu = new com.softwaredevelopment.level.up_library.ClassificationMenu.ClassificationMenu();
        pnlMACLMenu = new com.softwaredevelopment.level.up_library.MACLMenu.MACLMenu();
        ratingMenu1 = new com.softwaredevelopment.level.up_library.RatingMenu.RatingMenu();
        statusMenu1 = new com.softwaredevelopment.level.up_library.StatusMenu.StatusMenu();
        yearMenu1 = new com.softwaredevelopment.level.up_library.YearMenu.YearMenu();
        tbpGameEntries = new javax.swing.JTabbedPane();
        srpGameEntries = new javax.swing.JScrollPane();
        pnlGameEntries = new javax.swing.JPanel();
        pnlGameEntry = new com.softwaredevelopment.level.up_library.GameEntry.GameEntry();
        mnuTitlebar = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        optSave = new javax.swing.JMenuItem();
        optLoad = new javax.swing.JMenuItem();
        optQuit = new javax.swing.JMenuItem();
        menGame = new javax.swing.JMenu();
        optAddNew = new javax.swing.JMenuItem();
        optUpdate = new javax.swing.JMenuItem();
        optRemove = new javax.swing.JMenuItem();
        menHelp = new javax.swing.JMenu();
        optOnlineDocs = new javax.swing.JMenuItem();
        optManual = new javax.swing.JMenuItem();
        optAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Level-Up Library - Main Window");
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setName("MainWindow"); // NOI18N

        srpSidebar.setBorder(null);
        srpSidebar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        srpSidebar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        srpSidebar.setHorizontalScrollBar(null);
        srpSidebar.setMinimumSize(new java.awt.Dimension(220, 100));
        srpSidebar.setPreferredSize(new java.awt.Dimension(220, 100));

        pnlSidebar.setMinimumSize(new java.awt.Dimension(210, 29));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(210, 458));
        pnlSidebar.setLayout(new org.jdesktop.swingx.VerticalLayout());
        pnlSidebar.add(pnlSearchMenu);

        lblFilters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilters.setText("Filters");
        lblFilters.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblFilters.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFilters.setMinimumSize(new java.awt.Dimension(31, 20));
        lblFilters.setName(""); // NOI18N
        lblFilters.setPreferredSize(new java.awt.Dimension(31, 25));
        pnlSidebar.add(lblFilters);
        pnlSidebar.add(pnlClassificationMenu);
        pnlSidebar.add(pnlMACLMenu);
        pnlSidebar.add(ratingMenu1);
        pnlSidebar.add(statusMenu1);
        pnlSidebar.add(yearMenu1);

        srpSidebar.setViewportView(pnlSidebar);

        srpGameEntries.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        srpGameEntries.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlGameEntries.setLayout(new org.jdesktop.swingx.VerticalLayout());
        pnlGameEntries.add(pnlGameEntry);

        srpGameEntries.setViewportView(pnlGameEntries);

        tbpGameEntries.addTab("tab1", srpGameEntries);

        menFile.setText("File");

        optSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optSave.setText("Save");
        menFile.add(optSave);

        optLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optLoad.setText("Load");
        menFile.add(optLoad);

        optQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optQuit.setText("Quit");
        menFile.add(optQuit);

        mnuTitlebar.add(menFile);

        menGame.setText("Game");

        optAddNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optAddNew.setText("Add New");
        menGame.add(optAddNew);

        optUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        optUpdate.setText("Update");
        menGame.add(optUpdate);

        optRemove.setText("Remove");
        menGame.add(optRemove);

        mnuTitlebar.add(menGame);

        menHelp.setText("Help");

        optOnlineDocs.setText("Online Documentation");
        menHelp.add(optOnlineDocs);

        optManual.setText("Manual");
        menHelp.add(optManual);

        optAbout.setText("About");
        menHelp.add(optAbout);

        mnuTitlebar.add(menHelp);

        setJMenuBar(mnuTitlebar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(srpSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tbpGameEntries, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srpSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(tbpGameEntries)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFilters;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menGame;
    private javax.swing.JMenu menHelp;
    private javax.swing.JMenuBar mnuTitlebar;
    private javax.swing.JMenuItem optAbout;
    private javax.swing.JMenuItem optAddNew;
    private javax.swing.JMenuItem optLoad;
    private javax.swing.JMenuItem optManual;
    private javax.swing.JMenuItem optOnlineDocs;
    private javax.swing.JMenuItem optQuit;
    private javax.swing.JMenuItem optRemove;
    private javax.swing.JMenuItem optSave;
    private javax.swing.JMenuItem optUpdate;
    private com.softwaredevelopment.level.up_library.ClassificationMenu.ClassificationMenu pnlClassificationMenu;
    private javax.swing.JPanel pnlGameEntries;
    private com.softwaredevelopment.level.up_library.GameEntry.GameEntry pnlGameEntry;
    private com.softwaredevelopment.level.up_library.MACLMenu.MACLMenu pnlMACLMenu;
    private com.softwaredevelopment.level.up_library.SearchMenu.SearchMenu pnlSearchMenu;
    private javax.swing.JPanel pnlSidebar;
    private com.softwaredevelopment.level.up_library.RatingMenu.RatingMenu ratingMenu1;
    private javax.swing.JScrollPane srpGameEntries;
    private javax.swing.JScrollPane srpSidebar;
    private com.softwaredevelopment.level.up_library.StatusMenu.StatusMenu statusMenu1;
    private javax.swing.JTabbedPane tbpGameEntries;
    private com.softwaredevelopment.level.up_library.YearMenu.YearMenu yearMenu1;
    // End of variables declaration//GEN-END:variables
}
