/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.softwaredevelopment.level.up_library.SearchMenu;

import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;

/**
 *
 * @author dylan
 */
public class SearchMenu extends javax.swing.JPanel {

    /**
     * Creates new form SearchMenu
     */
    public SearchMenu() {
        initComponents();
    }
    
    /**
     * My Variables and Methods
     */
    public static ImageIcon icnCollapsedIcon = new ImageIcon("C:\\Users\\dylan\\School\\Year_12\\Software_Development\\Unit 4\\Level-Up_Library\\Level-Up_Library\\src\\main\\resources\\Collapsed.png");
    public static ImageIcon icnExpandedIcon = new ImageIcon("C:\\Users\\dylan\\School\\Year_12\\Software_Development\\Unit 4\\Level-Up_Library\\Level-Up_Library\\src\\main\\resources\\Expanded.png");
    
    public static String advancedPrevious = "N/A";
    
    public static String doLogicalComparisons(String strStates) {
        /**
         *************KEY**************
         * OS = Opening search
         * CS = Closing search
         * AWO = Advanced was open
         * AWC = Advanced was closed
         * SIO = Search is open
         * OA = Opening Advanced
         * CA = Closing advanced
         */
        
        Map<String, String> finalStates = new HashMap<String, String>();
        finalStates.put("CS, AWO", "false, false"); // Closing search, advanced was closed
        finalStates.put("CS, AWC", "false, false"); // Closing search, advanced was open
        finalStates.put("OS, AWO", "true, true"); // Opening search, advanced was closed
        finalStates.put("OS, AWC", "true, false"); // Opening search, advanced was open
        finalStates.put("SIO, OA", "true, true"); // Search is open, opening advanced
        finalStates.put("SIO, CA", "true, false"); // Search is open, closing advanced
        
        return finalStates.get(strStates);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpSearchCategory = new javax.swing.ButtonGroup();
        btnSearchToggle = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();
        pnlSearch.setVisible(false);
        txtSearchQuery = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pnlAdvancedSearch = new javax.swing.JPanel();
        pnlAdvancedSearch.setVisible(false);
        lblCategory = new javax.swing.JLabel();
        rtbTitle = new javax.swing.JRadioButton();
        rtnNotes = new javax.swing.JRadioButton();
        cbxExactSearch = new javax.swing.JCheckBox();
        btnAdvancedToggle = new javax.swing.JButton();
        btnAdvancedToggle.setVisible(false);
        advancedPrevious = "AWC";

        btnSearchToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Collapsed.png"))); // NOI18N
        btnSearchToggle.setText("Search");
        btnSearchToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSearchToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSearchToggle.setIconTextGap(53);
        btnSearchToggle.setMaximumSize(new java.awt.Dimension(130, 23));
        btnSearchToggle.setMinimumSize(new java.awt.Dimension(190, 29));
        btnSearchToggle.setPreferredSize(new java.awt.Dimension(130, 29));
        btnSearchToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchToggleActionPerformed(evt);
            }
        });

        pnlSearch.setBackground(new java.awt.Color(255, 0, 0));
        pnlSearch.setMinimumSize(new java.awt.Dimension(190, 10));
        pnlSearch.setPreferredSize(new java.awt.Dimension(190, 36));

        txtSearchQuery.setText("Search");
        txtSearchQuery.setMinimumSize(new java.awt.Dimension(71, 22));

        btnSearch.setText("Search");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(13, 13, 13))
        );

        pnlAdvancedSearch.setBackground(new java.awt.Color(0, 0, 255));
        pnlAdvancedSearch.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlAdvancedSearch.setPreferredSize(new java.awt.Dimension(178, 114));

        lblCategory.setText("Category:");

        bgpSearchCategory.add(rtbTitle);
        rtbTitle.setSelected(true);
        rtbTitle.setText("Title");

        bgpSearchCategory.add(rtnNotes);
        rtnNotes.setText("Notes");

        cbxExactSearch.setText("Exact Match");
        cbxExactSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cbxExactSearch.setIconTextGap(5);

        javax.swing.GroupLayout pnlAdvancedSearchLayout = new javax.swing.GroupLayout(pnlAdvancedSearch);
        pnlAdvancedSearch.setLayout(pnlAdvancedSearchLayout);
        pnlAdvancedSearchLayout.setHorizontalGroup(
            pnlAdvancedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdvancedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdvancedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory)
                    .addComponent(rtbTitle)
                    .addComponent(rtnNotes)
                    .addComponent(cbxExactSearch))
                .addGap(84, 84, 84))
        );
        pnlAdvancedSearchLayout.setVerticalGroup(
            pnlAdvancedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdvancedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtnNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxExactSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdvancedToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Collapsed.png"))); // NOI18N
        btnAdvancedToggle.setText("Advanced");
        btnAdvancedToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAdvancedToggle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAdvancedToggle.setIconTextGap(42);
        btnAdvancedToggle.setMaximumSize(new java.awt.Dimension(135, 29));
        btnAdvancedToggle.setMinimumSize(null);
        btnAdvancedToggle.setPreferredSize(new java.awt.Dimension(178, 29));
        btnAdvancedToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvancedToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdvancedToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAdvancedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearchToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdvancedToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdvancedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvancedToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvancedToggleActionPerformed
        boolean advancedState = pnlAdvancedSearch.isVisible();
        String searchCode = "SIO";
        String advancedCode = "N/A";
        
        if (advancedState == true) advancedCode = "CA";
        else if (advancedState == false) advancedCode = "OA";
        
        advancedPrevious = advancedCode;
        
        String newStates = doLogicalComparisons(searchCode + ", " + advancedCode);
        
        String[] bools = newStates.split(", ");
        
        pnlSearch.setVisible(Boolean.parseBoolean(bools[0]));
        btnAdvancedToggle.setVisible(Boolean.parseBoolean(bools[0]));
        pnlAdvancedSearch.setVisible(Boolean.parseBoolean(bools[1]));
        
        if (pnlAdvancedSearch.isVisible()) btnAdvancedToggle.setIcon(icnExpandedIcon);
        else btnAdvancedToggle.setIcon(icnCollapsedIcon);
    }//GEN-LAST:event_btnAdvancedToggleActionPerformed

    private void btnSearchToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchToggleActionPerformed
        boolean searchState = pnlSearch.isVisible();
        boolean advancedState = pnlAdvancedSearch.isVisible();
        String searchCode = "N/A";
        String advancedCode = "N/A";
        
        if (searchState == true) searchCode = "CS";
        else if (searchState == false) searchCode = "OS";
        
        if (advancedState == true) advancedCode = "AWO";
        else if (advancedState == false) advancedCode = "AWC";
        
        if (searchCode == "OS") advancedCode = advancedPrevious;
        
        String newStates = doLogicalComparisons(searchCode + ", " + advancedCode);
        
        advancedPrevious = advancedCode;
        
        String[] bools = newStates.split(", ");
        
        pnlSearch.setVisible(Boolean.parseBoolean(bools[0]));
        btnAdvancedToggle.setVisible(Boolean.parseBoolean(bools[0]));
        pnlAdvancedSearch.setVisible(Boolean.parseBoolean(bools[1]));
        
        if (pnlSearch.isVisible()) btnSearchToggle.setIcon(icnExpandedIcon);
        else btnSearchToggle.setIcon(icnCollapsedIcon);
    }//GEN-LAST:event_btnSearchToggleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpSearchCategory;
    private javax.swing.JButton btnAdvancedToggle;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchToggle;
    private javax.swing.JCheckBox cbxExactSearch;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JPanel pnlAdvancedSearch;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JRadioButton rtbTitle;
    private javax.swing.JRadioButton rtnNotes;
    private javax.swing.JTextField txtSearchQuery;
    // End of variables declaration//GEN-END:variables
}
