/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.softwaredevelopment.level.up_library.GameEntry;

/**
 *
 * @author dylan
 */
public class GameEntry extends javax.swing.JPanel {

    /**
     * Creates new form GameEntry
     */
    public GameEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSpacerFront = new javax.swing.JLabel();
        lblBoxArtImage = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        lblClassification = new javax.swing.JLabel();
        lblMACL = new javax.swing.JLabel();
        lblReleaseYear = new javax.swing.JLabel();
        lblPlayStatus = new javax.swing.JLabel();
        starRating1 = new com.softwaredevelopment.level.up_library.GameEntry.StarRating();

        org.jdesktop.swingx.HorizontalLayout horizontalLayout1 = new org.jdesktop.swingx.HorizontalLayout();
        horizontalLayout1.setGap(5);
        setLayout(horizontalLayout1);
        add(lblSpacerFront);

        lblBoxArtImage.setText("Box Art");
        lblBoxArtImage.setToolTipText("");
        add(lblBoxArtImage);

        lblGameName.setText("Title");
        add(lblGameName);

        lblClassification.setText("Classification");
        add(lblClassification);

        lblMACL.setText("MACL");
        add(lblMACL);

        lblReleaseYear.setText("Release Year");
        add(lblReleaseYear);

        lblPlayStatus.setText("Play Status");
        add(lblPlayStatus);
        add(starRating1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBoxArtImage;
    private javax.swing.JLabel lblClassification;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblMACL;
    private javax.swing.JLabel lblPlayStatus;
    private javax.swing.JLabel lblReleaseYear;
    private javax.swing.JLabel lblSpacerFront;
    private com.softwaredevelopment.level.up_library.GameEntry.StarRating starRating1;
    // End of variables declaration//GEN-END:variables
}
